# Generated by Django 3.2.6 on 2021-08-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorthen', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlwithaccount',
            name='shorthen_link_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='urlwithoutaccount',
            name='shorthen_link_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
